# Generated by Django 2.2 on 2020-11-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20201116_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passwrod',
            field=models.IntegerField(),
        ),
    ]
